modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/JDKDigital/productive-bees/issues"
license="MIT"

[[mods]] #mandatory
modId="productivebees"
version="${file.jarVersion}"
displayName="Productive Bees"
updateJSONURL="https://raw.githubusercontent.com/JDKDigital/productive-bees/dev-1.18/versions.json"
# displayURL="http://example.com/"
logoFile="logo.png"
credits="Thanks to me"
authors="LobsterJonn"
description='''
Useful bees
'''

[[dependencies.productivebees]] #optional
    modId="forge"
    mandatory=true
    versionRange="[40.0.18,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.productivebees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
